### ISSUE TITLE
Crash when opening issue from notification

### ISSUE THREAD

**Issue by mueller-ma** [slapperwan/gh4a#1078]
When I receive a notification for issue https://github.com/openhab/openhab-core/pull/1505 and I open it, that app crashes:

````
2021-05-20 20:41:12.414 9772-9772/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gh4a, PID: 9772
    io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:49)
        at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onError(SingleOnAssembly.java:75)
        at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onError(SingleOnAssembly.java:75)
        at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onError(ReactiveLoaders.java:51)
        at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33)
        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at androidx.loader.content.Loader.deliverResult(Loader.java:132)
        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:85)
        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:82)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
        at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onError(SingleOnAssembly.java:75)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
      ComposedException 1 :
    	com.squareup.moshi.JsonDataException: Expected one of [added_to_project, assigned, base_ref_changed, base_ref_force_pushed, closed, comment_deleted, commented, committed, connected, convert_to_draft, converted_note_to_issue, cross-referenced, demilestoned, deployed, disconnected, head_ref_deleted, head_ref_force_pushed, head_ref_restored, labeled, locked, marked_as_duplicate, mentioned, merged, moved_columns_in_project, milestoned, pinned, ready_for_review, referenced, removed_from_project, renamed, reopened, reviewed, review_dismissed, review_requested, review_request_removed, subscribed, transferred, unassigned, unlabeled, unlocked, unmarked_as_duplicate, unpinned, unsubscribed, user_blocked] but was automatic_base_change_succeeded at path $.items[20].event
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:244)
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:213)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
        at com.meisolsson.githubsdk.model.$AutoValue_IssueEvent$MoshiJsonAdapter.fromJson($AutoValue_IssueEvent.java:148)
        at com.meisolsson.githubsdk.model.$AutoValue_IssueEvent$MoshiJsonAdapter.fromJson($AutoValue_IssueEvent.java:29)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75)
[...]
````

I was subscribed to this issue with a `@<team>` mention and the GitHub website shows "team mention" as reason for this to show up in my inbox. I don't see "team mention" in the list of expected values above, so maybe this causes the crash.

**Comment by maniac103** [comment]
> but was automatic_base_change_succeeded at path $.items[20].event

Rather sounds like some rebasing stuff? I'll update the bindings.

**Comment by mueller-ma** [comment]
Right, I didn't catch that in the stack trace.

**Comment by Fs00** [comment]
@maniac103 I see that the missing enum value has been added to the bindings, so this can be closed.
