### ISSUE TITLE
crash when trying to view PR

### ISSUE THREAD

**Issue by casperdcl** [slapperwan/gh4a#1169]
```
# logcat -b crash
01-09 09:21:00.005 28092 28092 E AndroidRuntime: FATAL EXCEPTION: main
01-09 09:21:00.005 28092 28092 E AndroidRuntime: Process: com.gh4a, PID: 28092
01-09 09:21:00.005 28092 28092 E AndroidRuntime: com.squareup.moshi.JsonDataException: Expected one of [completed, in_progress, queued, requested] but was waiting at path $.check_runs[2].status
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:258)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:227)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.meisolsson.githubsdk.model.$AutoValue_CheckRun$MoshiJsonAdapter.fromJson($AutoValue_CheckRun.java:96)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.meisolsson.githubsdk.model.$AutoValue_CheckRun$MoshiJsonAdapter.fromJson($AutoValue_CheckRun.java:33)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.meisolsson.githubsdk.model.$AutoValue_CheckRunsResponse$MoshiJsonAdapter.fromJson($AutoValue_CheckRunsResponse.java:42)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.meisolsson.githubsdk.model.$AutoValue_CheckRunsResponse$MoshiJsonAdapter.fromJson($AutoValue_CheckRunsResponse.java:21)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Observable.subscribe(Observable.java:12267)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:63)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribe(Single.java:3603)01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
01-09 09:21:00.005 28092 28092 E AndroidRuntime:at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.run(Thread.java:764)
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Observable.singleOrError(Observable.java:11650)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at retrofit2.adapter.rxjava2.RxJava2CallAdapter.adapt(RxJava2CallAdapter.java:79)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:89)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.reflect.Proxy.invoke(Proxy.java:1006)01-09 09:21:00.006 28092 28092 E AndroidRuntime:at $Proxy22.getCheckRunsForRef(Unknown Source)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:489)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.onActivityCreated(PullRequestConversationFragment.java:127)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.viewpager.widget.ViewPager.setOffscreenPageLimit(ViewPager.java:856)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.BasePagerActivity.updateTabVisibility(BasePagerActivity.java:143)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.BasePagerActivity.invalidatePages(BasePagerActivity.java:61)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.BasePagerActivity.invalidateTabs(BasePagerActivity.java:65)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.activities.PullRequestActivity.lambda$load$6(PullRequestActivity.java:514)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.activities.PullRequestActivity.lambda$load$6$PullRequestActivity(Unknown Source:0)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.activities.-$$Lambda$PullRequestActivity$nFWg86hv32nRF6uhTT2bLAk52TI.accept(Unknown Source:4)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onLoadFinished(ReactiveLoaders.java:55)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:35)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.loader.content.Loader.deliverResult(Loader.java:132)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$1.accept(RxLoaderCallbacks.java:80)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at android.os.Handler.handleCallback(Handler.java:873)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at android.os.Handler.dispatchMessage(Handler.java:99)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at android.os.Looper.loop(Looper.java:214)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at android.app.ActivityThread.main(ActivityThread.java:7063)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.reflect.Method.invoke(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.map(Single.java:3008)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:490)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 42 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.map(Single.java:3008)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:491)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 42 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.map(Single.java:3008)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:492)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 42 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.zipArray(Single.java:1974)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.zip(Single.java:1553)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:505)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 42 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribeOn(Single.java:3675)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.-$$Lambda$M4WxcKwRhxdwJE_KviDWjmlm4R8.apply(Unknown Source:0)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.compose(Single.java:2064)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0(LoadingFragmentBase.java:84)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0$LoadingFragmentBase(Unknown Source:0)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.-$$Lambda$LoadingFragmentBase$ezeDyxD-UcvSxmfC2g4G7aT29vY.apply(Unknown Source:6)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.compose(Single.java:2064)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:517)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 42 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.observeOn(Single.java:3120)01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 49 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.wrap(Single.java:1477)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:... 48 more
01-09 09:21:00.006 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at io.reactivex.Single.subscribeOn(Single.java:3675)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.ReactiveType$Single.subscribeOn(ReactiveType.java:27)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
01-09 09:21:00.006 28092 28092 E AndroidRuntime:at androidx.loader.content.Loader.forceLoad(Loader.java:347)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.loader.content.Loader.startLoading(Loader.java:285)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:... 38 more
01-09 09:21:00.007 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at io.reactivex.Single.observeOn(Single.java:3120)01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.ReactiveType$Single.observeOn(ReactiveType.java:36)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:... 53 more
01-09 09:21:00.007 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at io.reactivex.Single.wrap(Single.java:1477)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at io.reactivex.Single.compose(Single.java:2064)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0(LoadingFragmentBase.java:85)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.gh4a.fragment.LoadingFragmentBase.lambda$makeLoaderSingle$0$LoadingFragmentBase(Unknown Source:0)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.gh4a.fragment.-$$Lambda$LoadingFragmentBase$ezeDyxD-UcvSxmfC2g4G7aT29vY.apply(Unknown Source:6)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at io.reactivex.Single.compose(Single.java:2064)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.loadCommitStatusesIfOpen(PullRequestConversationFragment.java:517)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at com.gh4a.fragment.PullRequestConversationFragment.onActivityCreated(PullRequestConversationFragment.java:127)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:... 38 more
01-09 09:21:00.007 28092 28092 E AndroidRuntime: Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at dalvik.system.VMStack.getThreadStackTrace(Native Method)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at java.lang.Thread.getStackTrace(Thread.java:1538)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:at io.reactivex.Single.wrap(Single.java:1477)
01-09 09:21:00.007 28092 28092 E AndroidRuntime:... 44 more
```

**Comment by Fs00** [comment]
Thanks for the report @casperdcl. Could you please give us a link to the PR that caused the crash?

**Comment by casperdcl** [comment]
https://github.com/iterative/terraform-provider-iterative/pull/340

**Comment by ShareASmile** [comment]
Viewing this PR producing a crash everytime in Octaroid v4.6.9 (latest on fdroid)
https://github.com/TeamNewPipe/NewPipeExtractor/pull/944

I stumbled upon this issue when i was about to open a new one.

**Comment by Fs00** [comment]
@ShareASmile I can reproduce it too. Can you still open an issue so that we can track it separately?

**Comment by ShareASmile** [comment]
I have opened a new issue in #1253
