### ISSUE TITLE
LICENSE ighack

### ISSUE THREAD

**Issue by leifi9** [slapperwan/gh4a#1277]
### Error stack trace
```
com.squareup.moshi.JsonDataException: Expected an int but was 2304312446 at path $.total_count
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:926)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.meisolsson.githubsdk.model.AutoValue_SearchPage$MoshiJsonAdapter.fromJson(AutoValue_SearchPage.java:73)
	at com.meisolsson.githubsdk.model.AutoValue_SearchPage$MoshiJsonAdapter.fromJson(AutoValue_SearchPage.java:25)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.singleOrError(Observable.java:11667)
	at retrofit2.adapter.rxjava2.RxJava2CallAdapter.adapt(RxJava2CallAdapter.java:79)
	at retrofit2.HttpServiceMethod$CallAdapted.adapt(HttpServiceMethod.java:148)
	at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:132)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy18.searchCode(Unknown Source)
	at com.gh4a.fragment.SearchFragment.makeCodeSearchSingle(SearchFragment.java:343)
	at com.gh4a.fragment.SearchFragment.loadPage(SearchFragment.java:167)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:115)
	at com.gh4a.fragment.PagedDataBaseFragment.$r8$lambda$FsLutP86jPFthU7tNzgg7SaI2jg(Unknown Source:0)
	at com.gh4a.fragment.PagedDataBaseFragment$$ExternalSyntheticLambda3.apply(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:530)
	at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableScanSeed.subscribeActual(ObservableScanSeed.java:47)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	... 8 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.utils.RxUtils.searchPageAdapter(RxUtils.java:186)
	at com.gh4a.fragment.SearchFragment.lambda$makeCodeSearchSingle$5(SearchFragment.java:344)
	at com.gh4a.fragment.SearchFragment.$r8$lambda$HDFB-Wc0g9NRbsZSGu7xPmZSfEk(Unknown Source:0)
	at com.gh4a.fragment.SearchFragment$$ExternalSyntheticLambda3.apply(Unknown Source:0)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.SearchFragment.makeCodeSearchSingle(SearchFragment.java:344)
	... 28 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 30 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:116)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:122)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.subscribeOn(Single.java:3740)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
	at com.gh4a.BaseActivity$$ExternalSyntheticLambda9.apply(Unknown Source:0)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:123)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.observeOn(Single.java:3161)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
	... 29 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 28 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Single.toObservable(Single.java:4075)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:124)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.flatMap(Observable.java:8615)
	at io.reactivex.Observable.flatMap(Observable.java:8568)
	at io.reactivex.Observable.flatMap(Observable.java:8535)
	at io.reactivex.Observable.flatMap(Observable.java:8506)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:115)
	at com.gh4a.fragment.PagedDataBaseFragment.onRefresh(PagedDataBaseFragment.java:77)
	at com.gh4a.fragment.SearchFragment.loadResults(SearchFragment.java:291)
	at com.gh4a.fragment.SearchFragment.onQueryTextSubmit(SearchFragment.java:207)
	at androidx.appcompat.widget.SearchView.onSubmitQuery(SearchView.java:1198)
	at androidx.appcompat.widget.SearchView$7.onEditorAction(SearchView.java:1175)
	at android.widget.TextView.onEditorAction(TextView.java:7075)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at android.view.inputmethod.InputConnectionWrapper.performEditorAction(InputConnectionWrapper.java:205)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:363)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:610)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.scanWith(Observable.java:11555)
	at io.reactivex.Observable.scan(Observable.java:11519)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:125)
	... 16 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.filter(Observable.java:8421)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:130)
	... 16 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.subscribeOn(Observable.java:12361)
	at com.philosophicalhacker.lib.ReactiveType$Observable.subscribeOn(ReactiveType.java:49)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
	at androidx.loader.content.Loader.forceLoad(Loader.java:347)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
	at androidx.loader.content.Loader.startLoading(Loader.java:285)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at androidx.lifecycle.LiveData.observe(LiveData.java:205)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
	at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
	at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
	at com.philosophicalhacker.lib.LoadRequest.execute(LoadRequest.java:21)
	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderObservable.subscribeActual(ReactiveLoaders.java:24)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:132)
	... 16 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.observeOn(Observable.java:10009)
	at io.reactivex.Observable.observeOn(Observable.java:9930)
	at com.philosophicalhacker.lib.ReactiveType$Observable.observeOn(ReactiveType.java:58)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
	... 36 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at io.reactivex.Observable.wrap(Observable.java:4087)
	at io.reactivex.Observable.compose(Observable.java:6417)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:131)
	... 16 more

```

**Comment by sebastien46** [comment]
Can be closed, fixed by [667022f](https://github.com/slapperwan/gh4a/commit/667022fa9dccde026fb4cd0ddec105bab84c2bc1)
