### ISSUE TITLE
Look like json numbers are being parsed as Int32. They appear to require at least a int64

### ISSUE THREAD

**Issue by uxmal** [slapperwan/gh4a#1332]
### Error stack trace
```
com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Expected an int but was 2149728112 at path $.items[5].payload.comment.pull_request_review_id at $.items[5].payload.comment.pull_request_review_id
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:101)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.internal.NonNullJsonAdapter.fromJson(NonNullJsonAdapter.java:43)
	at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:61)
	at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:23)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.squareup.moshi.JsonDataException: Expected an int but was 2149728112 at path $.items[5].payload.comment.pull_request_review_id
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:926)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.meisolsson.githubsdk.model.$AutoValue_ReviewComment$MoshiJsonAdapter.fromJson($AutoValue_ReviewComment.java:154)
	at com.meisolsson.githubsdk.model.$AutoValue_ReviewComment$MoshiJsonAdapter.fromJson($AutoValue_ReviewComment.java:31)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.meisolsson.githubsdk.model.payload.$AutoValue_PullRequestReviewCommentPayload$MoshiJsonAdapter.fromJson($AutoValue_PullRequestReviewCommentPayload.java:59)
	at com.meisolsson.githubsdk.model.payload.$AutoValue_PullRequestReviewCommentPayload$MoshiJsonAdapter.fromJson($AutoValue_PullRequestReviewCommentPayload.java:25)
	at com.meisolsson.githubsdk.core.GitHubEventAdapter.readPayload(GitHubEventAdapter.java:193)
	at com.meisolsson.githubsdk.core.GitHubEventAdapter.fromJson(GitHubEventAdapter.java:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:383)
	at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:269)
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
	... 34 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.singleOrError(Observable.java:11667)
	at retrofit2.adapter.rxjava2.RxJava2CallAdapter.adapt(RxJava2CallAdapter.java:79)
	at retrofit2.HttpServiceMethod$CallAdapted.adapt(HttpServiceMethod.java:148)
	at retrofit2.HttpServiceMethod.invoke(HttpServiceMethod.java:132)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy15.getUserReceivedEvents(Unknown Source)
	at com.gh4a.fragment.PrivateEventListFragment.loadPage(PrivateEventListFragment.java:38)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:115)
	at com.gh4a.fragment.PagedDataBaseFragment.$r8$lambda$FsLutP86jPFthU7tNzgg7SaI2jg(Unknown Source:0)
	at com.gh4a.fragment.PagedDataBaseFragment$$ExternalSyntheticLambda3.apply(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
	at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
	at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:530)
	at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableScanSeed.subscribeActual(ObservableScanSeed.java:47)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	... 8 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:116)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.map(Single.java:3045)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:122)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.subscribeOn(Single.java:3740)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
	at com.gh4a.BaseActivity$$ExternalSyntheticLambda9.apply(Unknown Source:0)
	at io.reactivex.Single.compose(Single.java:2078)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:123)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.observeOn(Single.java:3161)
	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
	... 29 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.wrap(Single.java:1491)
	... 28 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Single.toObservable(Single.java:4075)
	at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1(PagedDataBaseFragment.java:124)
	... 26 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.flatMap(Observable.java:8615)
	at io.reactivex.Observable.flatMap(Observable.java:8568)
	at io.reactivex.Observable.flatMap(Observable.java:8535)
	at io.reactivex.Observable.flatMap(Observable.java:8506)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:115)
	at com.gh4a.fragment.PagedDataBaseFragment.onRefresh(PagedDataBaseFragment.java:77)
	at com.gh4a.BaseFragmentPagerActivity.onRefresh(BaseFragmentPagerActivity.java:47)
	at com.gh4a.activities.home.HomeActivity.onRefresh(HomeActivity.java:400)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:208)
	at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:121)
	at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7544)
	at android.view.View.draw(View.java:25085)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.draw(View.java:25180)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.draw(View.java:25180)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1179)
	at android.view.View.draw(View.java:25180)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1161)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5706)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.scanWith(Observable.java:11555)
	at io.reactivex.Observable.scan(Observable.java:11519)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:125)
	... 66 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.filter(Observable.java:8421)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:130)
	... 66 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.subscribeOn(Observable.java:12361)
	at com.philosophicalhacker.lib.ReactiveType$Observable.subscribeOn(ReactiveType.java:49)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
	at androidx.loader.content.Loader.forceLoad(Loader.java:347)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
	at androidx.loader.content.Loader.startLoading(Loader.java:285)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at androidx.lifecycle.LiveData.observe(LiveData.java:205)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
	at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
	at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
	at com.philosophicalhacker.lib.LoadRequest.execute(LoadRequest.java:21)
	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderObservable.subscribeActual(ReactiveLoaders.java:24)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:132)
	... 66 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.observeOn(Observable.java:10009)
	at io.reactivex.Observable.observeOn(Observable.java:9930)
	at com.philosophicalhacker.lib.ReactiveType$Observable.observeOn(ReactiveType.java:58)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
	... 86 more
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at io.reactivex.Observable.wrap(Observable.java:4087)
	at io.reactivex.Observable.compose(Observable.java:6417)
	at com.gh4a.fragment.PagedDataBaseFragment.load(PagedDataBaseFragment.java:131)
	... 66 more

```

**Comment by vvb2060** [comment]
https://github.com/Meisolsson/GitHubSdk/blob/5fb203615c977e399fd4adebea2e824f75c81cc1/library/src/main/java/com/meisolsson/githubsdk/model/ReviewComment.java#L44

**Comment by j0057** [comment]
Hi, this seems to be happening a lot, any chance you can get the fix for this released?

**Comment by maniac103** [comment]
The fix for this is already released in version 4.6.12. You can get the APK from the releases page or from F-Droid. Play Store releases won't happen anymore, see #1319 for details on that.

**Comment by j0057** [comment]
I had no idea! Good to know that no updates will be coming through the Play store. I'll move over to the F-droid version then, thanks for the great app!
