### ISSUE TITLE
NPE in IssueActivity

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#463]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
at com.gh4a.activities.IssueActivity.onCreateOptionsMenu(IssueActivity.java:215)
at android.app.Activity.onCreatePanelMenu(Activity.java:3142)
at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:358)
[...]
```

**Comment by maniac103** [comment]
LOL, I just had the NPE when opening this very issue :) Should be easy to fix, just add a null check for mIsCollaborator. NPE probably happens if the issue loads faster than the collaborator status.
