### ISSUE TITLE
Comment deletion doesn't work

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#538]
```
03-22 18:17:20.679 4582-5071/com.gh4a W/System.err: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
03-22 18:17:20.679 4582-5071/com.gh4a W/System.err:     at org.eclipse.egit.github.core.client.GitHubClient.delete(GitHubClient.java:915)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at org.eclipse.egit.github.core.client.GitHubClient.delete(GitHubClient.java:642)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at org.eclipse.egit.github.core.service.PullRequestService.deleteComment(PullRequestService.java:552)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at com.gh4a.fragment.PullRequestFragment.deleteCommentInBackground(PullRequestFragment.java:239)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at com.gh4a.fragment.IssueFragmentBase$DeleteCommentTask.run(IssueFragmentBase.java:446)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at com.gh4a.fragment.IssueFragmentBase$DeleteCommentTask.run(IssueFragmentBase.java:430)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at com.gh4a.BackgroundTask.doInBackground(BackgroundTask.java:26)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at com.gh4a.BackgroundTask.doInBackground(BackgroundTask.java:7)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-22 18:17:20.680 4582-5071/com.gh4a W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by maniac103** [comment]
Yup, but only applies to PR comments, not to issue comments. Will check it.
