### ISSUE TITLE
Force close pretty on much every screen

### ISSUE THREAD

**Issue by ltGuillaume** [slapperwan/gh4a#548]
Using OctoDroid on Android 2.3.7 causes it to FC on pretty much every screen. Below is the logcat dump of such an occasion. This is after coming from the Open Issues and entering my Profile details (menu -> click on my user profile picture).
```
03-24 21:53:24.827 E/AndroidRuntime(14504): FATAL EXCEPTION: main
03-24 21:53:24.827 E/AndroidRuntime(14504): java.lang.StackOverflowError
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.text.Styled.measureText(Styled.java:442)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.text.Layout.measureText(Layout.java:1753)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.text.Layout.getLineMax(Layout.java:692)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.text.Layout.draw(Layout.java:344)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.text.BoringLayout.draw(BoringLayout.java:365)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.TextView.onDraw(TextView.java:4170)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6908)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1762)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.support.v4.view.ViewPager.draw(ViewPager.java:2407)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1380)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1140)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.View.draw(View.java:6911)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.widget.FrameLayout.draw(FrameLayout.java:357)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1959)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewRoot.draw(ViewRoot.java:1554)
03-24 21:53:24.827 E/AndroidRuntime(14504): 	at android.view.ViewRoot.performTraversals(ViewRoot.java:1263)
03-24 21:53:24.867 W/ActivityManager(  235):   Force finishing activity com.gh4a/.activities.UserActivity
03-24 21:53:25.368 W/ActivityManager(  235): Activity pause timeout for HistoryRecord{40a31558 com.gh4a/.activities.UserActivity}
03-24 21:53:26.088 I/CrashlyticsCore(14504): Crashlytics report upload complete: 58D587100089-0001-38A8-601C73AF6CEB
03-24 21:53:26.158 I/Process (14504): Sending signal. PID: 14504 SIG: 9
03-24 21:53:26.188 I/ActivityManager(  235): Process com.gh4a (pid 14504) has died.
03-24 21:53:26.198 I/WindowManager(  235): WIN DEATH: Window{40bd9860 com.gh4a/com.gh4a.activities.home.HomeActivity paused=false}
03-24 21:53:26.208 I/WindowManager(  235): WIN DEATH: Window{40713c48 com.gh4a/com.gh4a.activities.UserActivity paused=false}
```

**Comment by maniac103** [comment]
I'm aware of those StackOverflowErrors, but I wasn't aware that they're this frequent. Sadly, those crashes are one of the reasons the next Octodroid version won't have support for Gingerbread and ICS anymore. You're one of the (literally) one or two handful of Octodroid users on those versions left ;)
One might check whether the view hierarchy can be simplified a bit to make the call stack shorter, but TBH, I won't have time to do it anytime soon.

**Comment by ltGuillaume** [comment]
Yeah I get that Gingerbread support can be tough, and that not many people stick with their old devices for as long as I do, just didn't know if it was related to only that, or whether the problem was also present on newer OS versions (be it less frequently). Too bad, although I understand why you won't fix it, I do like OctoDroid best of the Github apps I've tried, it's impossible for me to use it: I usually bump into a FC within the first 10 seconds...

**Comment by Bluscream** [comment]
Isn't it called APNR rather than FC ?

**Comment by Tunous** [comment]
Closing because it's specific to versions of Android no longer supported by this app.
