### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by Cr321** [slapperwan/gh4a#647]
When I click the Trends Tag, the app crashed.
`07-12 22:17:10.941 11584-11584/com.gh4a E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.gh4a, PID: 11584
                                                          java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                              at java.util.regex.Matcher.reset(Matcher.java:177)
                                                              at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                              at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                              at com.vdurmont.emoji.EmojiParser.getAliasCandidates(EmojiParser.java:138)
                                                              at com.vdurmont.emoji.EmojiParser.parseToUnicode(EmojiParser.java:103)
                                                              at com.gh4a.adapter.TrendAdapter.onBindViewHolder(TrendAdapter.java:56)
                                                              at com.gh4a.adapter.TrendAdapter.onBindViewHolder(TrendAdapter.java:33)
                                                              at com.gh4a.adapter.RootAdapter.onBindViewHolder(RootAdapter.java:238)
                                                              at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
                                                              at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1761)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:598)
                                                              at android.view.View.layout(View.java:15748)
                                                              at android.view.ViewGroup.layout(ViewGroup.java:4970)
                                                              at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                              at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                          	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutC
`

**Comment by maniac103** [comment]
Looks like a trend entry without description. Should be an easy fix.
