### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sharkykh** [slapperwan/gh4a#654]
**Edit:** Might be related to #303... Not sure, that seems to have been fixed over a year ago.

I try to open [SickGear/SickGear](https://github.com/SickGear/SickGear) on the app (v4.1.1), but it crashes every time.

logcat:
```
08-04 04:29:14.224  8854  9001 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
08-04 04:29:14.224  8854  9001 E AndroidRuntime: Process: com.gh4a, PID: 8854
08-04 04:29:14.224  8854  9001 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HtmlUtils$HtmlToSpannedConverter.handleStartTag(HtmlUtils.java:393)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HtmlUtils$HtmlToSpannedConverter.startElement(HtmlUtils.java:799)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.push(Parser.java:795)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1062)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1017)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:566)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HtmlUtils$HtmlToSpannedConverter.convert(HtmlUtils.java:288)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HtmlUtils$Html.fromHtml(HtmlUtils.java:214)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HtmlUtils.encode(HtmlUtils.java:185)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HttpImageGetter$ObjectInfo.encode(HttpImageGetter.java:182)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.utils.HttpImageGetter.encode(HttpImageGetter.java:356)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment$FillReadmeTask.doInBackground(RepositoryFragment.java:329)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at com.gh4a.fragment.RepositoryFragment$FillReadmeTask.doInBackground(RepositoryFragment.java:309)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-04 04:29:14.224  8854  9001 E AndroidRuntime: 	... 3 more
```

**Comment by sharkykh** [comment]
This seems to work just fine on 26cda103f7c1b100cf91cddcffc102716ffae628,
so, nvm, probably fixed.
