### ISSUE TITLE
Crash when reactions update shortly after activity is closed

### ISSUE THREAD

**Issue by Tunous** [slapperwan/gh4a#662]
https://github.com/slapperwan/gh4a/blob/fa602bf41785b942dd7185a7bb35ee62beef4a9f/app/src/main/java/com/gh4a/fragment/IssueFragmentBase.java#L419

Got a crash there when closing long activity stack:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.supportInvalidateOptionsMenu()' on a null object reference
at com.gh4a.fragment.IssueFragmentBase.onReactionsUpdated(IssueFragmentBase.java:439)
at com.gh4a.widget.ReactionBar$ReactionDetailsCache.putEntry(ReactionBar.java:654)
at com.gh4a.widget.ReactionBar$FetchReactionTask.onPostExecute(ReactionBar.java:431)
at com.gh4a.widget.ReactionBar$AddReactionMenuHelper$1.onPostExecute(ReactionBar.java:573)
at com.gh4a.widget.ReactionBar$AddReactionMenuHelper$1.onPostExecute(ReactionBar.java:570)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6290)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by maniac103** [comment]
Fixed with https://github.com/slapperwan/gh4a/commit/0510c51ded399e672edb702ed96a1d2a5d1677f7
