### ISSUE TITLE
Crash on "search code"

### ISSUE THREAD

**Issue by Unpublished** [slapperwan/gh4a#822]
Happens since Rx merge in RepositoryActivity -> action bar menu -> Search code

```
E/AndroidRuntime(2871): FATAL EXCEPTION: main
E/AndroidRuntime(2871): Process: com.gh4a, PID: 2871
E/AndroidRuntime(2871): io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
E/AndroidRuntime(2871): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:75)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderObservable$1.onError(ReactiveLoaders.java:26)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33)
E/AndroidRuntime(2871): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
E/AndroidRuntime(2871): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
E/AndroidRuntime(2871): 	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:85)
E/AndroidRuntime(2871): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:82)
E/AndroidRuntime(2871): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:72)
E/AndroidRuntime(2871): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
E/AndroidRuntime(2871): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
E/AndroidRuntime(2871): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
E/AndroidRuntime(2871): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
E/AndroidRuntime(2871): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(2871): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(2871): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(2871): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/AndroidRuntime(2871): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(2871): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(2871): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime(2871):   ComposedException 1 :
E/AndroidRuntime(2871): 	java.lang.IllegalStateException: Unexpected search type -1
E/AndroidRuntime(2871): 		at com.gh4a.fragment.SearchFragment.loadPage(SearchFragment.java:166)
E/AndroidRuntime(2871): 		at com.gh4a.fragment.PagedDataBaseFragment.lambda$load$1$PagedDataBaseFragment(PagedDataBaseFragment.java:106)
E/AndroidRuntime(2871): 		at com.gh4a.fragment.PagedDataBaseFragment$$Lambda$0.apply(Unknown Source)
E/AndroidRuntime(2871): 		at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
E/AndroidRuntime(2871): 		at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
E/AndroidRuntime(2871): 		at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:490)
E/AndroidRuntime(2871): 		at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:451)
E/AndroidRuntime(2871): 		at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:153)
E/AndroidRuntime(2871): 		at io.reactivex.Observable.subscribe(Observable.java:10700)
E/AndroidRuntime(2871): 		at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
E/AndroidRuntime(2871): 		at io.reactivex.Observable.subscribe(Observable.java:10700)
E/AndroidRuntime(2871): 		at io.reactivex.internal.operators.observable.ObservableScanSeed.subscribeActual(ObservableScanSeed.java:47)
E/AndroidRuntime(2871): 		at io.reactivex.Observable.subscribe(Observable.java:10700)
E/AndroidRuntime(2871): 		at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
E/AndroidRuntime(2871): 		at io.reactivex.Observable.subscribe(Observable.java:10700)
E/AndroidRuntime(2871): 		at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
E/AndroidRuntime(2871): 		at io.reactivex.Scheduler$1.run(Scheduler.java:138)
E/AndroidRuntime(2871): 		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
E/AndroidRuntime(2871): 		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
E/AndroidRuntime(2871): 		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(2871): 		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
E/AndroidRuntime(2871): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(2871): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(2871): 		at java.lang.Thread.run(Thread.java:761)

```

**Comment by Unpublished** [comment]
Another crash I noticed happens if mRxLoader is null (due to app being too long in background and system low on memory, I guess)

Don't have a stacktrace yet tough.

for example here:
https://github.com/slapperwan/gh4a/blob/32d458a35591d624f12eb8bc667f56c68ab7f5af/app/src/main/java/com/gh4a/fragment/PagedDataBaseFragment.java#L122

**Comment by maniac103** [comment]
For the second one, I'd be interested in a stacktrace, because as far as I can tell it would mean onRefresh() is called before onActivityCreated(), and I'm not sure how that would happen.

I'll look into the first crash.

**Comment by Unpublished** [comment]
Thanks, can confirm the first crash is fixed!

Couldn't reproduce the second one yet.

Btw does the scroll bar act weird on this issue too on your end?
For me its size changes while scrolling in Octodroid.

**Comment by maniac103** [comment]
Yes, that's due to the list items having differing heights. Not much we can do about it.
