### ISSUE TITLE
Crash when trying to open the account menu

### ISSUE THREAD

**Issue by Porkepix** [slapperwan/gh4a#852]
Some time ago I did setup one or two accounts in Octodroid.

Now when trying to touch to open the accounts list in the menu, the whole application is crashing.

Here's joined the result of `adb logcat -v threadtime` when that happens:

```
05-13 20:15:48.512 21061 21061 D AndroidRuntime: Shutting down VM
05-13 20:15:48.514 21061 21061 E AndroidRuntime: FATAL EXCEPTION: main
05-13 20:15:48.514 21061 21061 E AndroidRuntime: Process: com.gh4a, PID: 21061
05-13 20:15:48.514 21061 21061 E AndroidRuntime: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at com.gh4a.Gh4Application.getAccounts(Gh4Application.java:158)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at com.gh4a.activities.home.HomeActivity.updateDrawerMode(HomeActivity.java:508)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at com.gh4a.activities.home.HomeActivity.onClick(HomeActivity.java:176)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.view.View.performClick(View.java:5280)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21239)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-13 20:15:48.514 21061 21061 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-13 20:15:48.515   915   935 D ActivityManager: New dropbox entry: com.gh4a, data_app_crash, 0bccc79e-dd30-466c-b325-eaa9b705a5ba
05-13 20:15:48.516   915   935 W ActivityManager:   Force finishing activity com.gh4a/.activities.home.HomeActivity
05-13 20:15:48.578 11161 21126 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1271 android.content.ContextWrapper.bindService:604 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192
05-13 20:15:48.589   915 20804 I OpenGLRenderer: Initialized EGL, version 1.4
05-13 20:15:48.641  4318  4334 I AsyncOpDispatcher: 35-GetDeviceDataUploadOptInStatusOperation
05-13 20:15:49.041   915   947 W ActivityManager: Activity pause timeout for ActivityRecord{be87188 u0 com.gh4a/.activities.home.HomeActivity t6689 f}
05-13 20:15:49.187  3817  3817 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@63ae96d time:97555721
05-13 20:15:49.294   915   968 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{8b5f084 u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t6618} time:97555827
```

Problem happens with latest F-droid version of the application on Android 6.0.1 with unmodified rom.

**Comment by slapperwan** [comment]
Done release, thank you 👍

**Comment by maniac103** [comment]
Thanks!
