### ISSUE TITLE
Crash when viewing pull request

### ISSUE THREAD

**Issue by runejuhl** [slapperwan/gh4a#864]
The app crashes when trying to open https://github.com/YorickPeterse/oga/pull/111

Here's some output from logcat:

~~~
Method exceeds compiler instruction limit: 25337 in void org.ccil.cowan.tagsoup.HTMLSchema.<init>()
io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
	at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onError(ReactiveLoaders.java:51)
	at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:85)
	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:82)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:44)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  ComposedException 1 :
	java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
		at com.gh4a.fragment.PullRequestFragment.lambda$onCreateDataSingle$13$PullRequestFragment(PullRequestFragment.java:301)
		at com.gh4a.fragment.PullRequestFragment$$Lambda$14.test(Unknown Source:2)
		at com.gh4a.utils.RxUtils.lambda$null$0$RxUtils(RxUtils.java:37)
		at com.gh4a.utils.RxUtils$$Lambda$13.apply(Unknown Source:4)
		at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:56)
		at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:59)
		at io.reactivex.Single.subscribe(Single.java:2692)
		at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
		at io.reactivex.Single.subscribe(Single.java:2692)
		at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:69)
		at io.reactivex.Single.subscribe(Single.java:2692)
		at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:69)
		at io.reactivex.Single.subscribe(Single.java:2692)
		at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
		at io.reactivex.Scheduler$1.run(Scheduler.java:138)
		at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
		at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by maniac103** [comment]
This was fixed by #860.
