### ISSUE TITLE
Adding reactions to comments sometimes fails silently (organization repositories only?)

### ISSUE THREAD

**Issue by smichel17** [slapperwan/gh4a#874]
Sometimes, adding a reaction fails silently. For example, I cannot react to any of the comments on https://github.com/LibreShift/red-moon/issues/243 — note that I *can* react to the issue itself, and that I *can* remove reactions added via the web UI.

I can also add reactions to comments on this repo. The only differences I can tell are that (1) that is an organizational repo where this is a personal repo and (2) I am a member of that organization.

Possible duplicate of #780, which is a GitHub API problem (not octodroid) and is supposedly fixed.

In the event that this is a duplicate or it is otherwise failing on GitHub's side, not ours, then I'd like to propose that we change the "silently" part :)

**Comment by Tunous** [comment]
Log from my device when I tried to add reaction to said repo:

```
Toggling reaction failed
com.gh4a.ApiRequestException: Not Found (404)
	at com.gh4a.utils.ApiHelpers.throwOnFailure(ApiHelpers.java:174)
	at com.gh4a.fragment.-$$Lambda$olmLiusFydaUVZ0nCrbumN6obZo.apply(Unknown Source:2)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:56)
	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
	at io.reactivex.Observable.subscribe(Observable.java:10700)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
	at io.reactivex.Single.subscribe(Single.java:2693)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$1.run(Scheduler.java:138)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1536)
	at io.reactivex.Single.map(Single.java:2200)
	at com.gh4a.fragment.IssueFragmentBase.addReaction(IssueFragmentBase.java:470)
	at com.gh4a.adapter.timeline.TimelineItemAdapter$2.addReaction(TimelineItemAdapter.java:127)
	at com.gh4a.adapter.timeline.CommentViewHolder.addReaction(CommentViewHolder.java:257)
	at com.gh4a.widget.ReactionBar.toggleReaction(ReactionBar.java:415)
	at com.gh4a.widget.ReactionBar.access$200(ReactionBar.java:50)
	at com.gh4a.widget.ReactionBar$ReactionUserPopup.toggleOwnReaction(ReactionBar.java:261)
	at com.gh4a.widget.ReactionBar$ReactionUserAdapter.onClick(ReactionBar.java:390)
	at android.view.View.performClick(View.java:6303)
	at android.view.View$PerformClick.run(View.java:24828)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6798)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1536)
	at io.reactivex.Single.map(Single.java:2200)
	at com.gh4a.widget.ReactionBar.toggleReaction(ReactionBar.java:416)
	... 12 more
```

**Comment by maniac103** [comment]
I asked support about this.

**Comment by maniac103** [comment]
Answer from support:
```
I believe that's an issue on our end related to OAuth Apps and creating reactions on issue comments in organization-owned repositories. I've asked the engineering team to look into this further. I can't promise an ETA, but we'll followup as soon as there's any news.
```

**Comment by maniac103** [comment]
Got another email from support:

> Just wanted to let you know that the team deployed some changes which should have fixed this problem. If you can still reproduce this — please let us know.

So please let me know if this is still an issue :-)

**Comment by smichel17** [comment]
Confirmed, seems to be working now.
