### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by jellybean13** [slapperwan/gh4a#888]
This unknown error occurs "Select branch as reference".

OctoDroid version: 4.4.0
Device: nikel
Android version: 6.0 (MRA58K)
SDK version: 23
OS: MediaTek AOSP
Logcat:
Here are logs from this device.

> Process: com.gh4a
> Flags: 0x38c8be44
> Package: com.gh4a v60 (4.4.0)
> Build: Xiaomi/nikel/nikel:6.0/MRA58K/1471320283:userdebug/test-keys
> 
> java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
> 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
> 	at java.util.ArrayList.get(ArrayList.java:313)
> 	at com.gh4a.adapter.RootAdapter.getItemFromAdapterPosition(RootAdapter.java:168)
> 	at com.gh4a.fragment.EventListFragment.onContextItemSelected(EventListFragment.java:470)
> 	at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:2502)
> 	at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:3319)
> 	at android.support.v4.app.FragmentController.dispatchContextItemSelected(FragmentController.java:357)
> 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:377)
> 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
> 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
> 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
> 	at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:5084)
> 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:766)
> 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
> 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:909)
> 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:899)
> 	at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
> 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1113)
> 	at android.widget.AdapterView.performItemClick(AdapterView.java:315)
> 	at android.widget.AbsListView.performItemClick(AbsListView.java:1193)
> 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
> 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4225)
> 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3931)
> 	at android.view.View.dispatchTouchEvent(View.java:9415)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2660)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2304)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
> 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2447)
> 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1766)
> 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:797)
> 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2408)
> 	at android.view.View.dispatchPointerEvent(View.java:9646)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4738)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4596)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
> 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4266)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
> 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4323)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6555)
> 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6529)
> 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6472)
> 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6727)
> 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
> 	at android.os.MessageQueue.nativePollOnce(Native Method)
> 	at android.os.MessageQueue.next(MessageQueue.java:328)
> 	at android.os.Looper.loop(Looper.java:164)
> 	at android.app.ActivityThread.main(ActivityThread.java:5692)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by maniac103** [comment]
What repo does this happen on?

**Comment by jellybean13** [comment]
This error has little to do with repos.

https://github.com/LineageOS/android_packages_apps_Apollo

https://github.com/LineageOS/android_packages_apps_Eleven

**Comment by jellybean13** [comment]
@maniac103 
This error has little to do with repos.
I watched some repos just now, but this error still exist.

https://github.com/LineageOS/android_packages_apps_Apollo

https://github.com/LineageOS/android_packages_apps_Eleven

**Comment by jellybean13** [comment]
@maniac103 
While loading issues in this repo, an unknown error happened just now.
Logcat:

> Process: com.gh4a
> Flags: 0x38c8be44
> Package: com.gh4a v60 (4.4.0)
> Build: Xiaomi/nikel/nikel:6.0/MRA58K/1471320283:userdebug/test-keys
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
> 	at android.support.design.widget.BottomSheetBehavior.onInterceptTouchEvent(BottomSheetBehavior.java:299)
> 	at com.gh4a.widget.ToggleableBottomSheetBehavior.onInterceptTouchEvent(ToggleableBottomSheetBehavior.java:25)
> 	at android.support.design.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:460)
> 	at android.support.design.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:499)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2143)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2666)
> 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2257)
> 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2447)
> 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1766)
> 	at android.app.Activity.dispatchTouchEvent(Activity.java:2798)
> 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
> 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
> 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2408)
> 	at android.view.View.dispatchPointerEvent(View.java:9646)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4738)
> 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4596)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
> 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4266)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
> 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4323)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
> 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
> 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
> 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
> 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6555)
> 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6529)
> 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6472)
> 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6727)
> 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
> 	at android.os.MessageQueue.nativePollOnce(Native Method)
> 	at android.os.MessageQueue.next(MessageQueue.java:328)
> 	at android.os.Looper.loop(Looper.java:164)
> 	at android.app.ActivityThread.main(ActivityThread.java:5692)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by maniac103** [comment]
Let's concentrate on the first one. From the log I gather you long-pressed an item in the news feed ... what kind of item was that? IOW, what content did that item have?

**Comment by jellybean13** [comment]
@maniac103 
I haven't use "News feed" so far, and I only use this client to watch repos and commits.

**Comment by maniac103** [comment]
So what exactly did you do when that crash occurred?

**Comment by jellybean13** [comment]
@maniac103 
I longpressed a commit.
The repos that I viewed were listed yesterday.
