### ISSUE TITLE
Error 404 when accessing pull requests of certain repo

### ISSUE THREAD

**Issue by PatrickvL** [slapperwan/gh4a#927]
When I access any pull request of this repository, even the most recent OctoDroid shows an 404 error, even though these pull requests can be accessed via the GitHub website just fine:
 https://github.com/XboxDev/nxdk

**Comment by maniac103** [comment]
This seems to work fine for me?!

**Comment by Riteo** [comment]
@maniac103 same thing! @PatrickvL can you still replicate this issue?

**Comment by matthiakl** [comment]
![Screenshot_20211016-001312](https://user-images.githubusercontent.com/23122583/137560877-3fec555c-ef64-47cf-a320-a1b38c7a1f00.png)
My device info:
OS: Lineage OS for microg 14.1
Android version: 7.1.2
API level: 25

Debug log:
<details>
<pre>
10-16 00:37:13.431 D/Gh4a    (21664): Loading data failed
10-16 00:37:13.431 D/Gh4a    (21664): com.gh4a.ApiRequestException: Not Found (404)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.gh4a.utils.ApiHelpers.mapToTrueOnSuccess(ApiHelpers.java:230)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.gh4a.utils.-$$Lambda$2f6WfUWdzRLSo0QeOs6els-qeiE.apply(lambda)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.tspoon.traceur.SingleOnAssembly$OnAssemblySingleObserver.onSuccess(SingleOnAssembly.java:70)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
10-16 00:37:13.431 D/Gh4a    (21664): 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.tspoon.traceur.SingleOnAssembly.subscribeActual(SingleOnAssembly.java:43)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.lang.Thread.run(Thread.java:761)
10-16 00:37:13.431 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.431 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.map(Single.java:3008)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.gh4a.utils.SingleFactory.isAppUserRepoCollaborator(SingleFactory.java:52)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.loadCollaboratorStatus(IssueListActivity.java:662)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.onCreate(IssueListActivity.java:155)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.Activity.performCreate(Activity.java:6684)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.os.Looper.loop(Looper.java:154)
10-16 00:37:13.431 D/Gh4a    (21664): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.lang.reflect.Method.invoke(Native Method)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-16 00:37:13.431 D/Gh4a    (21664): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-16 00:37:13.431 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.431 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.431 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.error(Single.java:562)
10-16 00:37:13.431 D/Gh4a    (21664): 	at io.reactivex.Single.error(Single.java:588)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.utils.RxUtils.lambda$null$8(RxUtils.java:84)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.utils.-$$Lambda$RxUtils$4bzKqm_11DC6MnoiGIaHFOeQ7GA.apply(lambda)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:60)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
10-16 00:37:13.432 D/Gh4a    (21664): 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Observable.subscribe(Observable.java:12267)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.subscribe(Single.java:3603)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.lang.Thread.run(Thread.java:761)
10-16 00:37:13.432 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.432 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.onErrorResumeNext(Single.java:3246)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.utils.RxUtils.lambda$mapFailureToValue$9(RxUtils.java:78)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.utils.-$$Lambda$RxUtils$FLtgRq07LaD9ncdvDF8t3wGEEN8.apply(lambda)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.compose(Single.java:2064)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.utils.SingleFactory.isAppUserRepoCollaborator(SingleFactory.java:55)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.loadCollaboratorStatus(IssueListActivity.java:662)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.onCreate(IssueListActivity.java:155)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.Activity.performCreate(Activity.java:6684)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.os.Looper.loop(Looper.java:154)
10-16 00:37:13.432 D/Gh4a    (21664): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.lang.reflect.Method.invoke(Native Method)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-16 00:37:13.432 D/Gh4a    (21664): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-16 00:37:13.432 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.432 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.432 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.432 D/Gh4a    (21664): 	at io.reactivex.Single.wrap(Single.java:1477)
10-16 00:37:13.432 D/Gh4a    (21664): 	... 16 more
10-16 00:37:13.432 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.434 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.434 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.subscribeOn(Single.java:3675)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:89)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.-$$Lambda$M4WxcKwRhxdwJE_KviDWjmlm4R8.apply(lambda)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.compose(Single.java:2064)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.BaseActivity.lambda$makeLoaderSingle$3(BaseActivity.java:609)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.BaseActivity.lambda$makeLoaderSingle$3$BaseActivity(BaseActivity.java)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.-$$Lambda$BaseActivity$ehFhy4ojrrBCrYnFCnkwVyGhQPU.apply(lambda)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.compose(Single.java:2064)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.loadCollaboratorStatus(IssueListActivity.java:663)
10-16 00:37:13.434 D/Gh4a    (21664): 	... 13 more
10-16 00:37:13.434 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.434 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.434 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.observeOn(Single.java:3120)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.gh4a.utils.RxUtils.doInBackground(RxUtils.java:90)
10-16 00:37:13.434 D/Gh4a    (21664): 	... 20 more
10-16 00:37:13.434 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.434 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.434 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.wrap(Single.java:1477)
10-16 00:37:13.434 D/Gh4a    (21664): 	... 19 more
10-16 00:37:13.434 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.434 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.434 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.subscribeOn(Single.java:3675)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.philosophicalhacker.lib.ReactiveType$Single.subscribeOn(ReactiveType.java:27)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:76)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.loader.content.Loader.forceLoad(Loader.java:347)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onStartLoading(RxLoaderCallbacks.java:65)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.loader.content.Loader.startLoading(Loader.java:285)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
10-16 00:37:13.434 D/Gh4a    (21664): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.Fragment.performStart(Fragment.java:2379)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2044)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.FragmentController.dispatchStart(FragmentController.java:187)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.Activity.performStart(Activity.java:6707)
10-16 00:37:13.434 D/Gh4a    (21664): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
10-16 00:37:13.434 D/Gh4a    (21664): 	... 9 more
10-16 00:37:13.434 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.434 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.434 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.434 D/Gh4a    (21664): 	at io.reactivex.Single.observeOn(Single.java:3120)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.philosophicalhacker.lib.ReactiveType$Single.observeOn(ReactiveType.java:36)
10-16 00:37:13.434 D/Gh4a    (21664): 	at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.onForceLoad(RxLoaderCallbacks.java:77)
10-16 00:37:13.434 D/Gh4a    (21664): 	... 32 more
10-16 00:37:13.435 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.435 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.435 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.435 D/Gh4a    (21664): 	at io.reactivex.Single.wrap(Single.java:1477)
10-16 00:37:13.435 D/Gh4a    (21664): 	at io.reactivex.Single.compose(Single.java:2064)
10-16 00:37:13.435 D/Gh4a    (21664): 	at com.gh4a.BaseActivity.lambda$makeLoaderSingle$3(BaseActivity.java:610)
10-16 00:37:13.435 D/Gh4a    (21664): 	at com.gh4a.BaseActivity.lambda$makeLoaderSingle$3$BaseActivity(BaseActivity.java)
10-16 00:37:13.435 D/Gh4a    (21664): 	at com.gh4a.-$$Lambda$BaseActivity$ehFhy4ojrrBCrYnFCnkwVyGhQPU.apply(lambda)
10-16 00:37:13.435 D/Gh4a    (21664): 	at io.reactivex.Single.compose(Single.java:2064)
10-16 00:37:13.435 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.loadCollaboratorStatus(IssueListActivity.java:663)
10-16 00:37:13.435 D/Gh4a    (21664): 	at com.gh4a.activities.IssueListActivity.onCreate(IssueListActivity.java:155)
10-16 00:37:13.435 D/Gh4a    (21664): 	at android.app.Activity.performCreate(Activity.java:6684)
10-16 00:37:13.435 D/Gh4a    (21664): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-16 00:37:13.435 D/Gh4a    (21664): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
10-16 00:37:13.435 D/Gh4a    (21664): 	... 9 more
10-16 00:37:13.435 D/Gh4a    (21664): Caused by: com.tspoon.traceur.TraceurException: Debug Exception generated at call site
10-16 00:37:13.435 D/Gh4a    (21664): 	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
10-16 00:37:13.435 D/Gh4a    (21664): 	at java.lang.Thread.getStackTrace(Thread.java:1566)
10-16 00:37:13.435 D/Gh4a    (21664): 	at io.reactivex.Single.wrap(Single.java:1477)
10-16 00:37:13.435 D/Gh4a    (21664): 	... 15 more
</pre>
</details>

**Comment by maniac103** [comment]
Interesting. I need to check [this](https://github.com/slapperwan/gh4a/blob/master/app/src/main/java/com/gh4a/utils/SingleFactory.java#L55) against [the docs](https://docs.github.com/en/rest/reference/repos#check-if-a-user-is-a-repository-collaborator) ... on a first glance the code is wrong, but why does it work for me?!

**Comment by matthiakl** [comment]
Workaround: Instead of logging in via OAuth I created a Personal Access Token with scope "repo,read:org,gist,notifications,user" (the same as used for OAuth). With this token everything works as expected.
