### ISSUE TITLE
Crashes on Actions notifications

### ISSUE THREAD

**Issue by casperdcl** [slapperwan/gh4a#956]
Crashes on startup (trying to display news feed).

Workaround is marking GitHub Actions notifications as read in a browser.

```
# logcat -b crash
02-17 12:16:39.539 28519 28519 E AndroidRuntime: FATAL EXCEPTION: main
02-17 12:16:39.539 28519 28519 E AndroidRuntime: Process: com.gh4a, PID: 28519
02-17 12:16:39.539 28519 28519 E AndroidRuntime: io.reactivex.exceptions.CompositeException: 1 exceptions occurred.
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.ReactiveLoaders$LoaderSingle$1.onError(ReactiveLoaders.java:51)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.RxLoaderCallbacks.onLoadFinished(RxLoaderCallbacks.java:33)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.support.v4.content.Loader.deliverResult(Loader.java:126)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.safeDeliverResult(RxLoaderCallbacks.java:109)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader.access$000(RxLoaderCallbacks.java:44)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:85)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.philosophicalhacker.lib.RxLoaderCallbacks$RxAndroidLoader$2.accept(RxLoaderCallbacks.java:82)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:44)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7063)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:   ComposedException 1 :
02-17 12:16:39.539 28519 28519 E AndroidRuntime:        com.squareup.moshi.JsonDataException: Expected one of [subscribed, manual, author, comment, mention, review_requested, team_mention, state_change, security_alert, assign] but was ci_activity at path $.items[0].reason
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:244)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:213)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.meisolsson.githubsdk.model.$AutoValue_NotificationThread$MoshiJsonAdapter.fromJson($AutoValue_NotificationThread.java:75)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.meisolsson.githubsdk.model.$AutoValue_NotificationThread$MoshiJsonAdapter.fromJson($AutoValue_NotificationThread.java:28)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:75)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:52)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:62)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.meisolsson.githubsdk.model.AutoValue_Page$MoshiJsonAdapter.fromJson(AutoValue_Page.java:20)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:34)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:42)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:25)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:118)02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:212)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.Observable.subscribe(Observable.java:10700)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.Single.subscribe(Single.java:2692)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.Single.subscribe(Single.java:2692)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.Single.subscribe(Single.java:2692)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.Scheduler$1.run(Scheduler.java:138)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:           at java.lang.Thread.run(Thread.java:764)
02-17 12:16:39.539 28519 28519 E AndroidRuntime:
```

Looks like `ci_activity` support needs to be added.

**Comment by maniac103** [comment]
Fixed in commit 7e0c05f5bc289afbb3ac62efef9270f82b3cb747
